### ISSUE TITLE
Milight app on Google play

### ISSUE THREAD

**Issue by Lstt2005** [sidoh/esp8266_milight_hub#20] opened 2017-03-24 08:51 UTC
Is Milight app (ver2 or ver3) in Google Play should see udp server and if yes, on wich port?
![24-03-2017 115146](https://cloud.githubusercontent.com/assets/6728198/24286892/43560404-1088-11e7-9259-8acffc68ba98.jpg)
If i lauch MiApp ver2 and use udp port 48899 - on serial console i see:
*WM: IP Address:
*WM: 192.168.137.215
Error, unexpected packet length (should always be 2-3, was: 5
Error, unexpected packet length (should always be 2-3, was: 10
Error, unexpected packet length (should always be 2-3, was: 5
Error, unexpected packet length (should always be 2-3, was: 10
Error, unexpected packet length (should always be 2-3, was: 5
Error, unexpected packet length (should always be 2-3, was: 10

**Comment by sidoh** [comment] 2017-03-24 16:17
No, I don't expect that it'd work right now.  Think issue is a duplicate of #15.  Let's take further conversation there.

**Closed by sidoh** 2017-03-24 16:17 UTC
