### ISSUE TITLE
Add option for fixed IP address

### ISSUE THREAD

**Issue by vzorglub** [sidoh/esp8266_milight_hub#355] opened 2018-10-31 13:28 UTC
Please add an option for fixed IP address, please. Thanks

**Comment by arcanatigris** [comment] 2018-11-01 15:05
Yes this would be very much appreciated, my domotica subnet only runs dhcp for this now.

**Comment by sidoh** [comment] 2018-11-03 19:46
Duplicate of #56.  There's a PR open for it as well: #351.

**Closed by sidoh** 2018-11-03 19:46 UTC
