### ISSUE TITLE
Special character '+' not supported in mqtt password

### ISSUE THREAD

**Issue by diabl0w** [sidoh/esp8266_milight_hub#234] opened 2018-02-18 16:04 UTC
Commands sent through mqtt don't work if a '+' is present in the mqtt password. Oddly enough, my broker says that the esp8266 is subscribing successfully in logs when first started up, but commands never go through. Without changing any configuration besides the password, commands now work.

EDIT: In addition to this, I knew something odd was going on after entering the password containing '+' in the webUI and then refreshing the page, the '+' symbol disappeared and was replaced with a *space*.

**Comment by sidoh** [comment] 2018-02-18 18:25
Aah, that's probably the fault of the crappy form handling in the UI.  Thanks for reporting.

If you're in a pinch, you can probably set it with the API.  I doubt this is happening at any level below the UI.

**Comment by diabl0w** [comment] 2018-02-18 19:55
Thanks for the quick reply, at the moment it's easier for me just to change
the password. If I ever decide to try the API and it is still not working
then I'll report back.

**Comment by sidoh** [comment] 2018-03-12 07:55
I think I'm not able to reproduce this.  Seems to work fine in my environment.

May I ask what browser you're using, @diabl0w?

**Comment by diabl0w** [comment] 2018-03-13 04:02
I know for a fact it happens on Android mobile using Chrome, I just double
checked. I will try on Firefox on my desktop when I get a chance.

**Comment by diabl0w** [comment] 2018-03-13 04:06
Yes it does occur on Firefox as well on desktop. Note that you must hit the submit button and then refresh the page to see the effect. Upon refreshing, the '+' symbol is replaced by a space

**Comment by sidoh** [comment] 2018-03-13 05:36
Interesting.  I was not able to reproduce it because it's fixed in 1.7!  I reverted back to 1.6 and it happened consistently.

The error was on the server end, not the client.  The client is sending the correct data.

One of the changes in 1.7 (thanks to @cmidgley!) is using the upstream HTTP server instead of the locally copy/pasted version, which included fixes for bugs which have since been patched.  

I think the upstream HTTP server must've patched this bug as well.

We have @cmidgley to thank for this one! :D

**Comment by diabl0w** [comment] 2018-03-26 21:06
great news! I'll wait for the release to confirm... thanks

**Closed** 2018-05-05 08:38 UTC
Labels: bug, staged-for-release
