### ISSUE TITLE
Selectize by Device Label instead of Hex ID

### ISSUE THREAD

**Issue by chris9012** [sidoh/esp8266_milight_hub#420] opened 2019-03-16 02:29 UTC
Any thoughts on adding the UI label? Would like to be able to work with my lights in the UI without having to keep record of or know the hex value. I was thinking instead of the selectize input being the DeviceID, a selectize can be the label of the device id. That way it is more user friendly to add meaning to your lights. A separate input box would show the Device ID. It may help though to also have a quick reference based on what is stored in settings as well for those trying to implement MQTT. They can use the quick reference to write out their MQTT topics by linking their description with the device ID without having to select each one in the list.

**Comment by sidoh** [comment] 2019-03-16 17:16
Duplicate of #210.  Thanks for the detailed suggestion.

**Closed by sidoh** 2019-03-16 17:16 UTC
