### ISSUE TITLE
All CCT Globes stop working if any are sent level =100 or color_temp = 370

### ISSUE THREAD

**Issue by Skinah** [sidoh/esp8266_milight_hub#214] opened 2018-02-11 07:05 UTC
Sending either level =100 or color_temp = 370 causes the EMH to stop controlling all CCT globes. Trying to send a simple on and off no longer works. When the EMH is in the broken state other globe types still work fine so it only causes CCT globes to break. Pressing reset in the control panel brings everything back.

This command breaks all CCT communication:
milight/commands/0x7/cct/1" {"state":"ON","level":100}

So sending these fail to work after the above has been sent:
milight/commands/0x7/cct/1" {"state":"OFF"}
milight/commands/0x7/cct/1" {"state":"ON"}

The work around I have found is by limiting my code to only send Level = 99 the crash or buffer overrun does not occur.

**Comment by sidoh** [comment] 2018-02-11 17:41
Think this is a duplicate of #170.

**Closed by sidoh** 2018-02-11 17:41 UTC
