### ISSUE TITLE
Define specific http port

### ISSUE THREAD

**Issue by agoralive** [sidoh/esp8266_milight_hub#531] opened 2019-09-26 20:51 UTC
To make the MDNS better on windows computers I would like to change the default webservice port from 80 into something else.

I have no problem gaining access to my Node-Red on raspberry.local:1880 on windows, but the milight-hub.local is not working (MAC works fine.....)

SO, could I change the port 80 to (I don't know) 12345 instead to make windows compatible?

**Comment by sidoh** [comment] 2019-09-26 21:11
I doubt the port is the issue.  You could try changing it manually if you like.

https://github.com/sidoh/esp8266_milight_hub/blob/master/src/main.cpp#L414
https://github.com/sidoh/esp8266_milight_hub/blob/master/lib/WebServer/MiLightHttpServer.h#L35

**Comment by sidoh** [comment] 2019-09-29 21:17
Please let me know if changing the port helps.

Setting for non-default HTTP port is also a duplicate of #183, so going to close.

**Closed by sidoh** 2019-09-29 21:17 UTC

**Comment by agoralive** [comment] 2019-12-11 05:25
Changing ports did not help, Windows stinks in this matter, Android systems does as well. Only sure bet for MDNS is the MAC/IOS devices
