### ISSUE TITLE
RGBW: Bulb white state not updating properly

### ISSUE THREAD

**Issue by Tanto4** [sidoh/esp8266_milight_hub#260] opened 2018-04-16 08:18 UTC
When selecting white mode for a bulb the state is not being update properly. 
this error also shows in the mqtt_update_topic_pattern

instead or returning the groupnumber it returns 
`milight/updatetopic/0x7410/rgbw/:group_`

where it should be: 
`milight/updatetopic/0x7410/rgbw/4`

also the preview color in the color picker stays in the last selected color (in the ui)
mqtt_state_topic_pattern is also not triggered

this is tested in 1.7.0-dev5

**Comment by sidoh** [comment] 2018-04-16 08:46
It appears your topic pattern was clipped.  It should be something like:

```
milight/updatetopic/:device_id/:device_type/:group_id
```

but you appear to have `:group_` instead of `:group_id`.

If this is not the case, please paste the output of the `/settings` endpoint, making sure to censor any passwords.

**Comment by Tanto4** [comment] 2018-04-16 09:30
ah thanks for the quick reply! This solves the MQTT problem with publishing, but when the mode is selected is `white` and the brightness is changed in the UI it still returns the previously last selected color, even when `computed_color` has been chosen. 

The colorpicker also stays in the last color even though white mode has been chosen.

**Comment by sidoh** [comment] 2018-04-16 17:59
What color picker?  The one in the espMH UI?

I'm not able to reproduce either of these things.

**Comment by Tanto4** [comment] 2018-04-16 18:50
When I change a bulb (brightness or color) the colorpicker shows this inthe espMH UI, this is also reflected in the mqtt topic `mqtt_state_topic_pattern`

But when the `white mode` is selected, the color in the square (in the esp UI) stays in the last selected color. Also in the mqtt log is shown that `mqtt_state_topic_pattern`  is not being triggered, only the `mqtt_update_topic_pattern` is triggered 


![screenshot_2018-04-16-20-43-54-170_at tripwire mqtt client](https://user-images.githubusercontent.com/38046330/38828675-0945b3e8-41b7-11e8-835c-ae181e2eaeb0.png)

**Comment by sidoh** [comment] 2018-04-17 16:10
State topic updates definitely work if everything is configured properly.  Can you paste your config?

Oh -- this is for RGBW.  I was looking at RGB+CCT.  Does look like this is a problem for RGBW.  I'll take a look later.

**Comment by sidoh** [comment] 2018-04-18 07:30
Should be fixed here:

https://github.com/sidoh/esp8266_milight_hub/releases/tag/1.7.0-dev6

**Closed** 2018-05-04 19:25 UTC
Labels: bug, staged-for-release
