### ISSUE TITLE
Support of Touch Screen LED RGBW FUT027

### ISSUE THREAD

**Issue by sisamiwe** [sidoh/esp8266_milight_hub#307] opened 2018-07-21 12:13 UTC
Hi,
I ordered a MiLight RGBW controller with 2.4Ghz remote. I got this one, which seems not to be supported.
![img_20180721_141026](https://user-images.githubusercontent.com/25724401/43035448-28d05360-8cf0-11e8-9998-4e37afe7625e.jpg)
I cannot sniff packets.

As per it seems to be a FUT027
[http://futlight.com/productdetails.aspx?id=199&typeid=146](url)
Can you help?
Thx

**Comment by sidoh** [comment] 2018-07-22 17:08
Think this is a duplicate of #266.

**Closed by sidoh** 2018-07-22 17:08 UTC

**Comment by khmann** [comment] 2018-07-24 04:10
Incorrect.  I own this module.  Notice how it has industry logos (CE something something) in the upper left where the word MiLight should be.  I have photos and SPI dumps.  It's a 6 byte protocol, it's actually pretty terrible, also the hardware is completely different inside.

**Comment by coolduke666** [comment] 2018-11-20 10:01
any solution for FUT027 support? milight oder clone? thx
