### ISSUE TITLE
Give group numbers a name 

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#462] opened 2019-05-19 09:54 UTC
Maybe a idea to give group numbers a name. When this can create maybe the plugin for domoticz can update as well. So when a device will add to domoticz you won't see:

```
Milight Hub - 0xAAAF/rgb_cct/1
Milight Hub - 0xAAAF/rgb_cct/2
Milight Hub - 0xAAAA/rgb_cct/1
```

but

```
Milight Hub - 0xAAAF/rgb_cct/Livingroom
Milight Hub - 0xAAAF/rgb_cct/BehindTV
Milight Hub - 0xAAAA/rgb_cct/Hallway
```

@galinette2000
What do you think about this?

**Comment by sidoh** [comment] 2019-05-19 15:40
I believe this is a duplicate of #210.

Although perhaps slightly different -- you're suggesting a label function for Group IDs, #210 suggests one for Device IDs.  They probably both make sense in their own way.

I'm wary of adding this kind of complexity, but open to it if it makes the software significantly easier to use.

Going to close as duplicate, but please add a comment on the other issue if it doesn't exactly cover what you're suggesting.

**Closed by sidoh** 2019-05-19 15:40 UTC
