### ISSUE TITLE
Change Name of ESP

### ISSUE THREAD

**Issue by druckgott** [sidoh/esp8266_milight_hub#197] opened 2018-01-05 14:18 UTC
Is it posbile to rename the hub so that the wifi name is not esp.....

**Comment by sidoh** [comment] 2018-01-09 19:01
Not currently, no.  Wouldn't be terribly hard to add support, though.

**Comment by druckgott** [comment] 2018-01-10 16:49
Is it not possible to use this command from. The wifi manager
wifi_station_set_hostname("CloudLamp");

**Comment by druckgott** [comment] 2018-01-10 17:02
If it's not working it's due to the version
https://github.com/tzapu/WiFiManager/issues/186

If I'm write you use the wifiManager or if I look on the code

**Comment by sidoh** [comment] 2018-01-10 19:36
Yes, that's how it's done.  I've done this for other projects.  The real work is exposing a setting for it.

**Comment by druckgott** [comment] 2018-01-10 20:03
Ah ok

**Comment by sidoh** [comment] 2018-03-12 07:00
Didn't catch this before, but this is a duplicate of #179

**Closed by sidoh** 2018-03-12 07:00 UTC
